{% set python_min = "3.10" %}
{% set name = "conda-devenv" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/conda-devenv/archive/{{ version }}.tar.gz
  sha256: bb95d7ecf63740183cdac54bab7462523cabf4479c08aec8edc7033da61c1dc3

build:
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - conda-devenv = conda_devenv.devenv:main
    - mamba-devenv = conda_devenv.devenv:mamba_main
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - colorama
    - conda >=4.3
    - jinja2
    - packaging
    - python >={{ python_min }}
    - pyyaml
    - typing_extensions

test:
  requires:
    - pytest-datadir >=1.0
    - pytest-mock
    - pytest-regressions
    - python {{ python_min }}
  imports:
    - conda_devenv
  commands:
    - conda-devenv --version
    - conda-devenv --help
    - pytest tests
  source_files:
    - tests

about:
  home: https://github.com/ESSS/conda-devenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to work with multiple projects in develop-mode using conda-env.
  doc_url: http://conda-devenv.readthedocs.io/
  dev_url: https://github.com/ESSS/conda-devenv

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - gqmelo
    - tadeu
    - prusse-martin
    - gcardozo123
