{% set name = "conda-devenv" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/ESSS/{{ name }}/archive/{{ version }}.zip
  sha256: 9e7b8187cfabe8c369ad1b73aac0f8da947b8c9655ba65617502e3dbbc7093c6

build:
  number: 2
  script: python -m pip install . --no-deps --ignore-installed
  entry_points:
    - conda-devenv = conda_devenv.devenv:main
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools_scm
  run:
    - conda  >=4.3
    - python
    - jinja2
    - pyyaml
    - six

test:
  requires:
    - pytest >=3
    - pytest-datadir >=1.0
    - pytest-mock
  imports:
    - conda_devenv
  commands:
    - conda-devenv --help
    - pytest tests
  source_files:
    - tests

about:
  home: https://github.com/ESSS/conda-devenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A tool to work with multiple projects in develop-mode using conda-env.'
  doc_url: http://conda-devenv.readthedocs.io/
  dev_url: https://github.com/ESSS/conda-devenv

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - gqmelo
    - tadeu
    - prusse-martin
    - oliveira-esss
