{% set name = "conda-devenv" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/conda-devenv/archive/{{ version }}.tar.gz
  sha256: b8542839e8c5081a5ad2568534e1f7281f4b17cd0ba6ec448a4b05379ce4f2ea

build:
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - conda-devenv = conda_devenv.devenv:main
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - conda  >=4.3
    - packaging
    - python >=3.6
    - jinja2
    - pyyaml

test:
  requires:
    - pytest >=3
    - pytest-datadir >=1.0
    - pytest-mock
  imports:
    - conda_devenv
  commands:
    - conda-devenv --version
    - conda-devenv --help
    - pytest tests
  source_files:
    - tests

about:
  home: https://github.com/ESSS/conda-devenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to work with multiple projects in develop-mode using conda-env.
  doc_url: http://conda-devenv.readthedocs.io/
  dev_url: https://github.com/ESSS/conda-devenv

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - gqmelo
    - tadeu
    - prusse-martin
    - oliveira-mauricio
    - gcardozo123
